### ISSUE TITLE
Current Hydro-Release broken for teleop_general

### ISSUE THREAD

**Issue by dornhege** [PR2/pr2_apps#18]
The current hydro-release 0.5.15 has only a partial update of the changed paths in pr2_mannequin_mode. The files are still in the package directory, while pr2_teleop_general already uses a launch file with subdirs.

This seems fixed in the hydro-devel branch, so it should just require a release of 0.5.18.

**Comment by UltronDestroyer** [comment]
Looks like I released it for Indigo but forgot to release the change into Hydro. Thanks @dornhege.
