### ISSUE TITLE
Catkinize pr2_apps

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_apps#2]
Catkinize and release pr2_apps; depends on catkinizing and releasing:
- [ ] app_manager (from multimaster_experimental)
- [ ] willow_maps (from wg_common)
- [ ] kinematics_msgs (from arm_navigation)
- [ ] pr2_common_action_msgs, pr2_tuck_arms_action (from PR2/pr2_common_actions#2 )

The dependency on `urdf` probably needs to be updated.

`arm_navigation` is no longer maintained; `pr2_teleop_general` may need to be dropped or upgraded.

**Comment by garaemon** [comment]
app_manager: https://github.com/willowgarage/multimaster_experimental/pull/1

**Comment by garaemon** [comment]
Where can I find willow_maps package?

**Comment by UltronDestroyer** [comment]
Do you want to catkinize this? I'm in the middle of doing it.

**Comment by garaemon** [comment]
Yes please catkinize and release it.

**Comment by UltronDestroyer** [comment]
If you'd like, http:github.com/pr2/Linux_networking is also needing to be
catkinized.

**Comment by UltronDestroyer** [comment]
Catkinized and released
